In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('coords.csv')

In [3]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z499,v499,x500,y500,z500,v500,x501,y501,z501,v501
0,Happy,0.512605,0.639472,-0.805672,0.999898,0.529573,0.574030,-0.764159,0.999680,0.541189,...,0.001391,0.0,0.560129,0.563537,0.015299,0.0,0.564114,0.557335,0.015723,0.0
1,Happy,0.511912,0.634413,-0.667480,0.999902,0.529541,0.570055,-0.631702,0.999693,0.541192,...,-0.000533,0.0,0.558557,0.561364,0.012006,0.0,0.562478,0.556144,0.012208,0.0
2,Happy,0.511814,0.632200,-0.616274,0.999906,0.529527,0.568534,-0.583080,0.999705,0.541191,...,0.000098,0.0,0.559250,0.560762,0.013252,0.0,0.563122,0.555721,0.013479,0.0
3,Happy,0.511790,0.631357,-0.658695,0.999910,0.529513,0.567838,-0.622637,0.999717,0.541183,...,-0.000421,0.0,0.559756,0.561194,0.012712,0.0,0.563608,0.556314,0.012903,0.0
4,Happy,0.511859,0.630418,-0.658592,0.999915,0.529522,0.567028,-0.619512,0.999729,0.541183,...,-0.000140,0.0,0.559967,0.560941,0.013037,0.0,0.563865,0.555981,0.013234,0.0

In [4]:
df.tail()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z499,v499,x500,y500,z500,v500,x501,y501,z501,v501
1267,Angry,0.516302,0.552749,-0.936681,0.999742,0.534953,0.473065,-0.884616,0.999315,0.548365,...,-0.000327,0.0,0.564933,0.463567,0.023377,0.0,0.570103,0.454199,0.024542,0.0
1268,Angry,0.513926,0.552787,-0.948968,0.999686,0.533652,0.473062,-0.896949,0.999146,0.547363,...,-0.000599,0.0,0.564165,0.463993,0.022654,0.0,0.569378,0.454942,0.023778,0.0
1269,Angry,0.512322,0.552391,-0.957932,0.999690,0.532776,0.472688,-0.902187,0.999156,0.546726,...,0.000003,0.0,0.563444,0.458141,0.024066,0.0,0.568242,0.451638,0.025017,0.0
1270,Angry,0.512820,0.552365,-0.974561,0.999678,0.532838,0.472598,-0.918659,0.999127,0.546659,...,0.000548,0.0,0.565150,0.453928,0.025274,0.0,0.569692,0.447956,0.026223,0.0
1271,Angry,0.513805,0.552479,-1.016119,0.999633,0.533580,0.472811,-0.962790,0.999015,0.547453,...,0.001304,0.0,0.566582,0.455460,0.026062,0.0,0.571250,0.449035,0.027086,0.0

In [5]:
df[df['class'] == 'Sad']

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z499,v499,x500,y500,z500,v500,x501,y501,z501,v501
293,Sad,0.567730,0.558242,-0.841291,0.999435,0.600577,0.485105,-0.794118,0.998495,0.618486,...,-0.001908,0.0,0.641085,0.484224,0.017450,0.0,0.646013,0.478508,0.017822,0.0
294,Sad,0.568249,0.572502,-0.624112,0.999485,0.600577,0.492436,-0.590785,0.998625,0.618277,...,-0.001745,0.0,0.642716,0.485946,0.017700,0.0,0.647692,0.479836,0.018154,0.0
295,Sad,0.568547,0.578416,-0.636522,0.999527,0.600550,0.495667,-0.600279,0.998736,0.617971,...,-0.002513,0.0,0.644807,0.486782,0.017255,0.0,0.649818,0.480953,0.017726,0.0
296,Sad,0.569019,0.582005,-0.604157,0.999569,0.600605,0.497865,-0.564804,0.998848,0.617928,...,-0.002672,0.0,0.644391,0.487584,0.017076,0.0,0.649449,0.481815,0.017531,0.0
297,Sad,0.569114,0.582642,-0.646494,0.999607,0.600885,0.498333,-0.604902,0.998948,0.618076,...,-0.002956,0.0,0.645325,0.491918,0.015803,0.0,0.650681,0.484490,0.016330,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,Sad,0.421914,0.612177,-0.570157,0.999481,0.457225,0.533784,-0.614767,0.998349,0.474463,...,-0.022974,0.0,0.497251,0.543712,-0.049446,0.0,0.503955,0.532318,-0.052895,0.0
791,Sad,0.421874,0.611995,-0.561871,0.999482,0.457197,0.533738,-0.606288,0.998350,0.474330,...,-0.023483,0.0,0.497799,0.543943,-0.051145,0.0,0.504325,0.533328,-0.054697,0.0
792,Sad,0.422144,0.609199,-0.567176,0.999469,0.457418,0.531562,-0.609596,0.998319,0.474565,...,-0.023776,0.0,0.501131,0.538314,-0.052498,0.0,0.507664,0.527748,-0.056189,0.0
793,Sad,0.432172,0.608820,-0.584651,0.999480,0.465178,0.528322,-0.621427,0.998358,0.484015,...,-0.022351,0.0,0.510236,0.535559,-0.046597,0.0,0.517070,0.524616,-0.049855,0.0
794,Sad,0.441909,0.608830,-0.610478,0.999486,0.474751,0.526792,-0.641799,0.998378,0.495019,...,-0.020967,0.0,0.519811,0.530756,-0.039931,0.0,0.526419,0.519394,-0.042706,0.0

In [6]:
X = df.drop('class', axis=1)
y = df['class']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [8]:
y_test

1212        Angry
1053        Angry
1159        Angry
281         Happy
878     Victories
          ...
155         Happy
470           Sad
725           Sad
685           Sad
356           Sad
Name: class, Length: 382, dtype: object

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [12]:
pipelines = {
    'lr':make_pipeline(StandardScaler(), LogisticRegression()),
    'rc':make_pipeline(StandardScaler(), RidgeClassifier()),
    'rf':make_pipeline(StandardScaler(), RandomForestClassifier()),
    'gb':make_pipeline(StandardScaler(), GradientBoostingClassifier()),
}

In [14]:
fit_models = {}
for algo, pipeline in pipelines.items():
    model = pipeline.fit(X_train, y_train)
    fit_models[algo] = model

/Users/hwan/Documents/ml/Analysis_System/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
fit_models

{'lr': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('logisticregression', LogisticRegression())]),
 'rc': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('ridgeclassifier', RidgeClassifier())]),
 'rf': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('randomforestclassifier', RandomForestClassifier())]),
 'gb': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('gradientboostingclassifier', GradientBoostingClassifier())])}

In [16]:
fit_models['rc'].predict(X_test)

array(['Angry', 'Angry', 'Angry', 'Happy', 'Victories', 'Angry', 'Sad',
       'Angry', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry',
       'Victories', 'Sad', 'Sad', 'Angry', 'Happy', 'Victories', 'Happy',
       'Sad', 'Victories', 'Sad', 'Victories', 'Angry', 'Angry', 'Sad',
       'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Happy',
       'Sad', 'Angry', 'Sad', 'Angry', 'Sad', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Angry', 'Angry', 'Victories', 'Angry',
       'Happy', 'Sad', 'Victories', 'Angry', 'Victories', 'Sad', 'Angry',
       'Victories', 'Sad', 'Sad', 'Angry', 'Angry', 'Angry', 'Sad', 'Sad',
       'Happy', 'Angry', 'Happy', 'Happy', 'Angry', 'Angry', 'Angry',
       'Happy', 'Victories', 'Angry', 'Victories', 'Happy', 'Sad', 'Sad',
       'Angry', 'Sad', 'Angry', 'Happy', 'Happy', 'Victories', 'Sad',
       'Happy', 'Angry', 'Sad', 'Sad', 'Sad', 'Angry', 'Happy', 'Sad',
       'Happy', 'Sad', 'Angry', 'Angry', 'Victories', 'Sad', 'Sad',
       'Happy', 'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Happy', 'Happy',
       'Victories', 'Happy', 'Angry', 'Angry', 'Sad', 'Sad', 'Sad', 'Sad',
       'Angry', 'Sad', 'Happy', 'Sad', 'Happy', 'Victories', 'Angry',
       'Happy', 'Happy', 'Angry', 'Angry', 'Happy', 'Angry', 'Sad', 'Sad',
       'Sad', 'Happy', 'Victories', 'Sad', 'Happy', 'Happy', 'Angry',
       'Sad', 'Victories', 'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Sad',
       'Sad', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry', 'Angry',
       'Angry', 'Happy', 'Victories', 'Sad', 'Happy', 'Sad', 'Victories',
       'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Angry', 'Sad',
       'Sad', 'Sad', 'Angry', 'Angry', 'Sad', 'Sad', 'Sad', 'Victories',
       'Sad', 'Victories', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry',
       'Angry', 'Angry', 'Victories', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad',
       'Sad', 'Angry', 'Sad', 'Happy', 'Sad', 'Happy', 'Angry', 'Angry',
       'Happy', 'Victories', 'Sad', 'Sad', 'Happy', 'Happy', 'Happy',
       'Sad', 'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Victories',
       'Angry', 'Sad', 'Happy', 'Happy', 'Happy', 'Sad', 'Sad',
       'Victories', 'Sad', 'Victories', 'Sad', 'Angry', 'Sad', 'Happy',
       'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Victories', 'Happy', 'Happy',
       'Victories', 'Happy', 'Angry', 'Happy', 'Sad', 'Sad', 'Happy',
       'Sad', 'Happy', 'Angry', 'Sad', 'Happy', 'Angry', 'Happy', 'Happy',
       'Angry', 'Angry', 'Happy', 'Sad', 'Sad', 'Sad', 'Victories',
       'Victories', 'Angry', 'Victories', 'Sad', 'Victories', 'Angry',
       'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Victories', 'Sad',
       'Angry', 'Sad', 'Victories', 'Victories', 'Angry', 'Sad', 'Happy',
       'Happy', 'Angry', 'Angry', 'Sad', 'Sad', 'Angry', 'Sad', 'Sad',
       'Angry', 'Sad', 'Happy', 'Angry', 'Happy', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Angry', 'Happy', 'Sad', 'Sad', 'Happy',
       'Happy', 'Sad', 'Sad', 'Sad', 'Victories', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Happy', 'Sad', 'Sad', 'Happy', 'Angry',
       'Angry', 'Angry', 'Happy', 'Sad', 'Angry', 'Happy', 'Sad', 'Angry',
       'Happy', 'Angry', 'Victories', 'Sad', 'Sad', 'Sad', 'Happy',
       'Happy', 'Victories', 'Sad', 'Sad', 'Happy', 'Angry', 'Victories',
       'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Victories', 'Angry', 'Angry',
       'Happy', 'Sad', 'Angry', 'Happy', 'Sad', 'Sad', 'Sad', 'Happy',
       'Sad', 'Victories', 'Angry', 'Sad', 'Sad', 'Sad', 'Angry',
       'Victories', 'Sad', 'Sad', 'Sad', 'Happy', 'Angry', 'Happy',
       'Angry', 'Sad', 'Angry', 'Sad', 'Angry', 'Victories', 'Victories',
       'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad'], dtype='<U9')

In [17]:
y_test

1212        Angry
1053        Angry
1159        Angry
281         Happy
878     Victories
          ...
155         Happy
470           Sad
725           Sad
685           Sad
356           Sad
Name: class, Length: 382, dtype: object

In [18]:
from sklearn.metrics import accuracy_score
import pickle

In [19]:
for algo, model in fit_models.items():
    yhat = model.predict(X_test)
    print(algo, accuracy_score(y_test, yhat))

lr 0.9973821989528796
rc 1.0
rf 1.0
gb 1.0

In [20]:
fit_models['rf'].predict(X_test)

array(['Angry', 'Angry', 'Angry', 'Happy', 'Victories', 'Angry', 'Sad',
       'Angry', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry',
       'Victories', 'Sad', 'Sad', 'Angry', 'Happy', 'Victories', 'Happy',
       'Sad', 'Victories', 'Sad', 'Victories', 'Angry', 'Angry', 'Sad',
       'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Happy',
       'Sad', 'Angry', 'Sad', 'Angry', 'Sad', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Angry', 'Angry', 'Victories', 'Angry',
       'Happy', 'Sad', 'Victories', 'Angry', 'Victories', 'Sad', 'Angry',
       'Victories', 'Sad', 'Sad', 'Angry', 'Angry', 'Angry', 'Sad', 'Sad',
       'Happy', 'Angry', 'Happy', 'Happy', 'Angry', 'Angry', 'Angry',
       'Happy', 'Victories', 'Angry', 'Victories', 'Happy', 'Sad', 'Sad',
       'Angry', 'Sad', 'Angry', 'Happy', 'Happy', 'Victories', 'Sad',
       'Happy', 'Angry', 'Sad', 'Sad', 'Sad', 'Angry', 'Happy', 'Sad',
       'Happy', 'Sad', 'Angry', 'Angry', 'Victories', 'Sad', 'Sad',
       'Happy', 'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Happy', 'Happy',
       'Victories', 'Happy', 'Angry', 'Angry', 'Sad', 'Sad', 'Sad', 'Sad',
       'Angry', 'Sad', 'Happy', 'Sad', 'Happy', 'Victories', 'Angry',
       'Happy', 'Happy', 'Angry', 'Angry', 'Happy', 'Angry', 'Sad', 'Sad',
       'Sad', 'Happy', 'Victories', 'Sad', 'Happy', 'Happy', 'Angry',
       'Sad', 'Victories', 'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Sad',
       'Sad', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry', 'Angry',
       'Angry', 'Happy', 'Victories', 'Sad', 'Happy', 'Sad', 'Victories',
       'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Angry', 'Sad',
       'Sad', 'Sad', 'Angry', 'Angry', 'Sad', 'Sad', 'Sad', 'Victories',
       'Sad', 'Victories', 'Victories', 'Sad', 'Happy', 'Angry', 'Angry',
       'Angry', 'Angry', 'Victories', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad',
       'Sad', 'Angry', 'Sad', 'Happy', 'Sad', 'Happy', 'Angry', 'Angry',
       'Happy', 'Victories', 'Sad', 'Sad', 'Happy', 'Happy', 'Happy',
       'Sad', 'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Victories',
       'Angry', 'Sad', 'Happy', 'Happy', 'Happy', 'Sad', 'Sad',
       'Victories', 'Sad', 'Victories', 'Sad', 'Angry', 'Sad', 'Happy',
       'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Victories', 'Happy', 'Happy',
       'Victories', 'Happy', 'Angry', 'Happy', 'Sad', 'Sad', 'Happy',
       'Sad', 'Happy', 'Angry', 'Sad', 'Happy', 'Angry', 'Happy', 'Happy',
       'Angry', 'Angry', 'Happy', 'Sad', 'Sad', 'Sad', 'Victories',
       'Victories', 'Angry', 'Victories', 'Sad', 'Victories', 'Angry',
       'Sad', 'Victories', 'Sad', 'Sad', 'Sad', 'Victories', 'Sad',
       'Angry', 'Sad', 'Victories', 'Victories', 'Angry', 'Sad', 'Happy',
       'Happy', 'Angry', 'Angry', 'Sad', 'Sad', 'Angry', 'Sad', 'Sad',
       'Angry', 'Sad', 'Happy', 'Angry', 'Happy', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Angry', 'Happy', 'Sad', 'Sad', 'Happy',
       'Happy', 'Sad', 'Sad', 'Sad', 'Victories', 'Sad', 'Angry', 'Sad',
       'Happy', 'Victories', 'Happy', 'Sad', 'Sad', 'Happy', 'Angry',
       'Angry', 'Angry', 'Happy', 'Sad', 'Angry', 'Happy', 'Sad', 'Angry',
       'Happy', 'Angry', 'Victories', 'Sad', 'Sad', 'Sad', 'Happy',
       'Happy', 'Victories', 'Sad', 'Sad', 'Happy', 'Angry', 'Victories',
       'Sad', 'Angry', 'Sad', 'Sad', 'Sad', 'Victories', 'Angry', 'Angry',
       'Happy', 'Sad', 'Angry', 'Happy', 'Sad', 'Sad', 'Sad', 'Happy',
       'Sad', 'Victories', 'Angry', 'Sad', 'Sad', 'Sad', 'Angry',
       'Victories', 'Sad', 'Sad', 'Sad', 'Happy', 'Angry', 'Happy',
       'Angry', 'Sad', 'Angry', 'Sad', 'Angry', 'Victories', 'Victories',
       'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad'], dtype=object)

In [21]:
y_test

1212        Angry
1053        Angry
1159        Angry
281         Happy
878     Victories
          ...
155         Happy
470           Sad
725           Sad
685           Sad
356           Sad
Name: class, Length: 382, dtype: object

In [22]:
with open('body_language.pkl', 'wb') as f:
    pickle.dump(fit_models['rf'], f)